---
title: "Exploration"
output: html_notebook
---
#Dataset 02
##Data loading

```{r}
library(data.table)
library(dplyr)
library(ggplot2)
dt_path <- "D:\\Users\\selautie\\Desktop\\KickClub Project\\Dataset_02_LendingClub\\Transformed\\loan.csv"
dt_ <- data.table::fread(dt_path, stringsAsFactors=TRUE)

```

##Data Exploration
Classiques
```{r}
str(dt_)
summary(dt_)
```

Descripteur (ratio NA's & classes de variables)
```{r}
sum_na <- sapply(dt_, function(col){sum(is.na(col))})
ratio_na <- sum_na/dim(dt_)[1]
which_class <- sapply(dt_, function(col){class(col)})
var_name <- names(dt_)

tmp <-data.frame(cbind(var_name,ratio_na, which_class,sum_na))
descriptor <- tmp %>% mutate(sum_na_n = as.numeric(as.character(descriptor$sum_na))) %>% select(-sum_na) %>% arrange(ratio_na)

descriptor
```
On remarque seulement 15 levels différents pour le ratio_na ==> na sont très probablement des na de groupe

```{r}
length(levels(descriptor$ratio_na))
ggplot(data.frame(x= descriptor$var_name, y = as.numeric(as.character(descriptor$ratio_na))), aes(x=reorder(x, y),y=y, col=which_class))+
        geom_point() +
        theme(axis.text.x = element_text(angle = 90, hjust = 1))
```
Liste des variable avec un taux na > 0,5
```{r}
descriptor$var_name[as.numeric(as.character(descriptor$ratio_na))>0.5]
```

